# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="ide_vs_studio"

[default]
account = "KQB07510"
user = "SNOWCR"
password = "@#Di#B!^0n%O3%"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
